# Default configuration for agentic-coder

# System settings
system:
  name: "agentic-coder"
  version: "0.1.0"
  debug: false
  log_level: "INFO"

# Agent configuration
agents:
  max_concurrent: 5
  default_timeout: 300
  max_iterations: 10
  enable_reflection: true
  enable_learning: true

# Memory configuration
memory:
  working_memory_size: 50
  episodic_memory_size: 1000
  semantic_memory_size: 10000
  
# LLM configuration
llm:
  default_model: "gpt-4"
  max_tokens: 4096
  temperature: 0.7
  top_p: 0.9
  
# Database configuration
databases:
  neo4j:
    uri: "bolt://localhost:7687"
    database: "agentic_coder"
  chroma:
    host: "localhost"
    port: 8001
    persist_directory: "./data/chroma_db"

# Tool configuration
tools:
  enable_file_operations: true
  enable_code_execution: true
  enable_web_search: false
  sandbox_mode: true
  allowed_extensions:
    - ".py"
    - ".js"
    - ".ts"
    - ".md"
    - ".txt"
    - ".json"
    - ".yaml"
    - ".yml"

# UI configuration
ui:
  console_width: 120
  enable_progress_bars: true
  show_timestamps: true
  theme: "default"